//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console4_DatabaseApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studid { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public Nullable<int> mobile { get; set; }
    }
}
