#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mydatabase")]
	public partial class Data1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Data1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mydatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
	public partial class customer
	{
		
		private System.Nullable<int> _custid;
		
		private string _custname;
		
		private System.Nullable<int> _custsalary;
		
		public customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custid", DbType="Int")]
		public System.Nullable<int> custid
		{
			get
			{
				return this._custid;
			}
			set
			{
				if ((this._custid != value))
				{
					this._custid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custname", DbType="VarChar(50)")]
		public string custname
		{
			get
			{
				return this._custname;
			}
			set
			{
				if ((this._custname != value))
				{
					this._custname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custsalary", DbType="Int")]
		public System.Nullable<int> custsalary
		{
			get
			{
				return this._custsalary;
			}
			set
			{
				if ((this._custsalary != value))
				{
					this._custsalary = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
